inherit_from: .rubocop_todo.yml

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - "db/**/*"

Layout/LineLength:
  Max: 120
  Exclude:
    - "bin/bundle"

Metrics/AbcSize:
  Exclude:
    - "bin/**/*"

Metrics/BlockLength:
  Exclude:
    - "Guardfile"

Metrics/CyclomaticComplexity:
  Exclude:
    - "bin/**/*"

Metrics/MethodLength:
  Exclude:
    - "bin/**/*"

Metrics/PerceivedComplexity:
  Exclude:
    - "bin/**/*"

Style/BlockComments:
  Exclude:
    - "spec/spec_helper.rb"

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
  
Style/ExpandPathArguments:
  Exclude:
    - "bin/**/*"

Style/FrozenStringLiteralComment:
  Exclude:
    - "db/schema.rb"

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Exclude:
    - "bin/**/*"

Style/NumericLiterals:
  Exclude:
    - "db/schema.rb"

Style/PerlBackrefs:
  Exclude:
    - "bin/**/*"

Style/RedundantBegin:
  Exclude:
    - "bin/**/*"

Style/RegexpLiteral:
  Exclude:
    - "Guardfile"

Style/SpecialGlobalVars:
  Exclude:
    - "bin/**/*"
Style/StringLiterals:
  EnforcedStyle: double_quotes
