# frozen_string_literal: true

# Autogenerated ApplicationController
class ApplicationController < ActionController::Base
  before_action :set_locale

  # Sets the language based on the client browser's first reported language
  #
  # @author Troy L. Marshall
  # @since 0.0.1
  def set_locale
    I18n.locale = extract_locale_from_accept_language_header
  end

  private

  def extract_locale_from_accept_language_header
    http_accept_language = request.env["HTTP_ACCEPT_LANGUAGE"]
    primary = http_accept_language.nil? ? "en" : http_accept_language.scan(/^[a-z]{2}/).first

    # Available locales set in config/initializers/locales.rb
    I18n.available_locales.include?(primary.to_sym) ? primary : I18n.default_locale
  end
end
